# Site settings
title: Jimmy Joseph
description: A blog of stuff I find interesting/learning
#baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://jimmyjoseph.co.uk" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Rustle my Jimmies
user_description: I like building things
user_title: Author, Blogger, Computer Scientist, Designer, Engineer...
email: jimmyjoseph@outlook.com
twitter_username: jimmyjoseph1295
github_username:  jimmyjoseph1295
gplus_username:  jimmyjoseph1295
#disqus_username: lorem_ipsum

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: Series
    url: /series
  - title: Tags
    url: /tags
  - title: About Me
    url: /about

# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
